# Generated by Django 4.0.2 on 2022-04-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('w', 'Womens Wear'), ('M', 'Mens Wear'), ('K', 'Kids Wear'), ('P', 'Party Bag'), ('H', 'Hand Bag'), ('S', 'Side Bag')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('used_for', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price', models.FloatField()),
                ('condition', models.CharField(blank=True, choices=[('G', 'Good'), ('O', 'old'), ('N', 'New')], max_length=10, null=True)),
                ('price_negotiable', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5, null=True)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='productimg')),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productimg')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.product')),
            ],
        ),
    ]
