# Generated by Django 4.0.2 on 2022-03-12 11:10

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('w', 'Womens Wear'), ('M', 'Mens Wear'), ('K', 'Kids Wear'), ('P', 'Party Bag'), ('H', 'Hand Bag'), ('S', 'Side Bag')], max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('item_price', models.FloatField()),
                ('condition', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=projects.models.filepath)),
                ('description', models.TextField()),
            ],
        ),
    ]
