# Generated by Django 3.2.5 on 2022-04-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='product',
            new_name='seller',
        ),
    ]
