# Generated by Django 3.2.5 on 2022-04-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20220424_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.product'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
