# Generated by Django 4.0.2 on 2022-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_negotiable',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('w', 'Womens Wear'), ('M', 'Mens Wear'), ('K', 'Kids Wear'), ('P', 'Party Bag'), ('H', 'Hand Bag'), ('S', 'Side Bag')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('G', 'Good'), ('O', 'old'), ('N', 'New')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
