# Generated by Django 4.0.2 on 2022-03-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_product_price_negotiable_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('w', 'Womens Wear'), ('M', 'Mens Wear'), ('K', 'Kids Wear'), ('P', 'Party Bag'), ('H', 'Hand Bag'), ('S', 'Side Bag')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('G', 'Good'), ('O', 'old'), ('N', 'New')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_negotiable',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
    ]
