# Generated by Django 4.0.2 on 2022-04-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
