# Generated by Django 4.0.2 on 2022-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
