# Generated by Django 4.0.2 on 2022-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_reviewrating_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
