# Generated by Django 3.2.5 on 2022-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='profileimg'),
        ),
    ]
